{
    "name": "Library Application",
    "summary": "Used for library management",
    "website": "https://bizzappdev.com",
    "author": "bizzappdev",
    "version": "15.0.1.0.0",
    "category": "uncategorized",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "data/book_details_sequence.xml",
        "data/author_details_sequence.xml",
        "data/library_details_sequence.xml",
        "data/member_details_sequence.xml",
        "data/bookloan_details_sequence.xml",
        "data/event_details_sequence.xml",
        "views/book_details_views.xml",
        "views/author_details_views.xml",
        "views/library_details_views.xml",
        "views/member_details_views.xml",
        "views/book_loan_details_views.xml",
        "views/event_details_views.xml",
        "views/book_menu_views.xml",
        "views/res_config_settings_views.xml",

    ],
    "application": True,
    "license": "LGPL-3",
}
